#!/bin/csh -f
#
# makediff old.tex new.tex
# generates  openmp-diff.tex and openmp-diff.pdf
# 
# the --math-markup flag is probably not needed.
#
# generates a lot of warning messages that can be ignored. 
# it also takes time to process, and appears to hang up, but be
# patient .. it takes a couple of minutes to complete on my
# MacBook Pro
#
# -- Richard Friedman (with help from Alex Duran) Oct 2014
##
rm -f openmp-diff.*
latexdiff --flatten --math-markup=whole -a ld-safe.txt --append-textcmd=plc,code,glossaryterm --exclude-textcmd="section,subsection,subsubsection" --ignore-latex-errors $1 $2 >! openmp-diff.tex
pdflatex -interaction=nonstopmode -file-line-error openmp-diff.tex
makeindex -s openmp-index.ist openmp-diff.idx
pdflatex -interaction=nonstopmode -file-line-error openmp-diff.tex
pdflatex -interaction=nonstopmode -file-line-error openmp-diff.tex
