# This specifies the OpenMP version which shows in all builds
OMPVERSION=Version 5.0

# This specifies the document version which only shows in release builds
DOCVERSION=Public Comment Draft
DOCDATE=July 2018

# these are the macros used to actually build the spec
VERSIONMACRO="\\def\\ompversion{$(OMPVERSION) -- GIT ref \\gitAbbrevHash{}}\\input{openmp}"
RELEASEMACRO="\\def\\ompversion{$(OMPVERSION) $(DOCVERSION), $(DOCDATE)}\\input{openmp}"

