version: 2
jobs:
  build:
    docker:
      - image: jprotze/latexdiff
    steps:
      - checkout
      - run:
          name: Generate openmp.pdf
          command: make
      - run:
          name: Generate openmp-diff-full.pdf
          command: make DIFF_FROM=$(git merge-base origin/master HEAD) openmp-diff-full.pdf
      - run:
          name: Generate openmp-diff-abridged.pdf
          command: make DIFF_FROM=$(git merge-base origin/master HEAD) openmp-diff-abridged.pdf 

      - store_artifacts:
          path: openmp.pdf
      - store_artifacts:
          path: openmp-diff-full.pdf
      - store_artifacts:
          path: openmp-diff-abridged.pdf
