version: 2
jobs:
  build:
    docker:
      - image: jprotze/latexdiff
    steps:
      - checkout
      - run:
          name: Generate openmp.pdf
          command: make
      - run:
          name: Generate openmp-diff-full.pdf
          command: make openmp-diff-full.pdf
      - run:
          name: Generate openmp-diff-abridged.pdf
          command: make openmp-diff-abridged.pdf

      - store_artifacts:
          path: openmp.pdf
      - store_artifacts:
          path: openmp-diff-full.pdf
      - store_artifacts:
          path: openmp-diff-abridged.pdf
